### ISSUE TITLE
Images in Rich Push Notifications still not working in FCM?

### ISSUE THREAD

**Issue by LiborZa** [customerio/customerio-ios#193]
Hello,
I am trying to implement rich notifications with images but it seems it's still not working in latest alpha `1.2.0-alpha.4` release. I added Notification Service Extension with this implementation:

```
import CioMessagingPush
import UserNotifications

class NotificationService: UNNotificationServiceExtension {

    override func didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
        MessagingPush.shared.didReceive(request, withContentHandler: contentHandler)
    }
    
    override func serviceExtensionTimeWillExpire() {
        MessagingPush.shared.serviceExtensionTimeWillExpire()
    }
}
```

This I have in podfile:

```
target 'xxx do
  use_frameworks!

  ...
  pod 'CustomerIOTracking', '1.2.0-alpha.4'
  pod 'CustomerIOMessagingPushFCM', '1.2.0-alpha.4'

end

target 'NotificationService' do
  use_frameworks!

  pod 'CustomerIOTracking', '1.2.0-alpha.4'
  pod 'CustomerIOMessagingPushFCM', '1.2.0-alpha.4'
end
```

I am trying example payload from documentation and notifications are coming with title and body but no image. I tried to change `didReceive` method to add text to title and it was working. So it seems notifications are handled by CustomerIO in extension but image is not processed. How can I fix it? What am I doing wrong?

Thanks for help

**Comment by lj-cio** [comment]
Hi @LiborZa, thank you for flagging this issue!  Our team is investigating this and it initially looks like a similar issue that was [reported earlier](https://github.com/customerio/customerio-ios/issues/159) that may have regressed.  

Can you try calling CustomerIO.initialize() inside of the Notification Service to see if it's the same issue? 
And also share the payload that you're using to test so we can take a look as well?

**Comment by LiborZa** [comment]
Hi @lj-cio , I am using example payload:

```
{
    "message": {
        "apns": {
            "payload": {
                "CIO": {
                    "push": {
                        "link": "remote-habits://deep?message=hello&message2=world",
                        "image": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpawsindoorssouthend.com%2Fwp-content%2Fuploads%2F2020%2F04%2Ftips-for-choosing-doggy-day-care.jpg"
                    }
                },
                "aps": {
                    "mutable-content": 1,
                    "alert": {
                        "title": "Title of your push goes here!",
                        "body": "Body of your push goes here!"
                    }
                }
            }
        }
    }
}
```

I am not sure where I should put `CustomerIO.initialize` so I put it to `didReceive` before trying to process notification content and it's still not working. When I tried to debug extension I see this:

```
[CIO] (siteid:6b60e) 🛑 4xx HTTP status code response.
Probably a bug? Response received, but status code = 400. malformed delivery id: .
```

**Comment by ami-aman** [comment]
Hi @LiborZa Thanks for sharing the payload. As LJ mentioned, this is a known issue and the team is investigating on this. As a workaround, we advice you to put the SDK initialisation code in Notification Extension in `didReceive` method as shown the snapshot below :

<img width="863" alt="Screenshot 2022-09-08 at 1 12 59 AM" src="https://user-images.githubusercontent.com/91549653/188963350-f7a51504-a533-4845-9346-cc33d89d69c8.png">

Also, I would suggest to try changing the image Url in the payload. (For eg, https://thumbs.dreamstime.com/b/bee-flower-27533578.jpg) 

Let us know if this helps to fix the issue you have :)

**Comment by LiborZa** [comment]
Hi @ami-aman  it helped to change image but I am not sure why. Calling init method didn't helped. 

Working: `https://thumbs.dreamstime.com/b/bee-flower-27533578.jpg`

Not working:
`https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpawsindoorssouthend.com%2Fwp-content%2Fuploads%2F2020%2F04%2Ftips-for-choosing-doggy-day-care.jpg`

**Comment by ami-aman** [comment]
Glad that the issue is fixed for you @LiborZa. Unfortunately, the former image link breaks randomly when downloading the image. We will make sure to update the sample payload in our docs as well, to avoid encountering the scenario again. Thanks for bringing this up. Greatly appreciate !

Now that the issue is resolved for you, I will go ahead and close the ticket. Feel free to comment if you face any other issue related to this ticket.

**Comment by jordanhailey** [comment]
Pasting the code from @ami-aman 's screenshot **[here](https://github.com/customerio/customerio-ios/issues/193#issuecomment-1239805432)** since we're seeing a lot of folks mistype the example code:

```swift
import UserNotifications
import CioMessagingPushAPN
import CioTracking

class NotificationService: UNNotificationServiceExtension {
  private let cioMessagingPush: MessagingPush = DI.shared.messagingPush

  override func didReceive(
    _ request: UNNotificationRequest,
    withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void
  ) {

    CustomerIO.initialize(siteld: Env.customerIOSiteId, apiKey: Env.customerIOApiKey, region: Region.US)
    let handled = cioMessagingPush.didReceive(request, withContentHandler: contentHandler)
    if !handled {
      contentHandler(request.content)
    }
  }

  override func serviceExtensionTimeWillExpire() {
    cioMessagingPush.serviceExtensionTimeWillExpire()
  }
}
```
