### ISSUE TITLE
COCOAPOD Missing for INApp messages

### ISSUE THREAD

**Issue by alpha-sagar** [customerio/customerio-ios#196]
Cocoapods available 
`pod 'CustomerIO/Tracking'`
`pod 'CustomerIO/MessagingPushAPN'`
But its not available for InApp Messages 
I tried by using like this `pod 'CustomerIO/MessagingInApp'` but no luck 
I know its in Beta but you can make cocoa pods available by which we can try and implement same

Thank you !

**Comment by Shahroz16** [comment]
Hey @alpha-sagar, thank you for raising this, you need to mention the version/tag as well. 
e.g, 
pod "CustomerIO/MessagingInApp", '~> 1.2.0-beta.1'

Let me know, if this doesn't work for you.

**Comment by alpha-sagar** [comment]
its not worked for me !
 ```
[!] CocoaPods could not find compatible versions for pod "CustomerIO/MessagingInApp":
In Podfile:
    CustomerIO/MessagingInApp (~> 1.2.0-beta.1)
None of your spec sources contain a spec satisfying the dependency: CustomerIO/MessagingInApp (~> 1.2.0-beta.1).
```

**Comment by alpha-sagar** [comment]
Issue not Fixed !
Still Ticket Closed ?

**Comment by ami-aman** [comment]
Hi @alpha-sagar 
`CustomerIO/MessagingInApp` is available on Cocoapods and as @Shahroz16 mentioned the latest tag is `1.2.0-beta.1`. You can find the related podspec here. 
https://github.com/CocoaPods/Specs/blob/master/Specs/a/d/9/CustomerIOMessagingInApp/1.2.0-beta.1/CustomerIOMessagingInApp.podspec.json

To help you with the issue you are facing, is it possible to share the Podfile here ? Meanwhile, can you try removing `Podfile.lock` file and `pod install` again ?

**Comment by alpha-sagar** [comment]
Thank you !
Its Working now ,
The dependant pods also need to be on the same version.

`pod 'CustomerIO/Tracking','~> 1.2.0-beta.1'`
`pod 'CustomerIO/MessagingPushAPN','~> 1.2.0-beta.1'`
`pod 'CustomerIOMessagingInApp','~> 1.2.0-beta.1'`

You can close the ticket now !
