### ISSUE TITLE
Opened event has never tracked

### ISSUE THREAD

**Issue by troy-oxstreet** [customerio/customerio-ios#197]
Hi,

I am using the 1.2.0-beta.1. Implemented and get Rich Notification work successfully. As the document, it said "If you already configured [rich push notifications](https://customer.io/docs/sdk/ios/rich-push/), the SDK will automatically track opened and delivered events for push notifications originating from Customer.io.". However, I have never gotten the Opened event from Broadcast > Newsletters reports.

My NotificationService
```
import UserNotifications
import CioTracking
import CioMessagingPush

class NotificationService: UNNotificationServiceExtension {
    override func didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
        CustomerIO.initialize(siteId: "", apiKey: "")
        let handled = MessagingPush.shared.didReceive(request, withContentHandler: contentHandler)
        if !handled {
            contentHandler(request.content)
        }
    }
    
    override func serviceExtensionTimeWillExpire() {
        MessagingPush.shared.serviceExtensionTimeWillExpire()
    }
}
```

**Comment by lj-cio** [comment]
Hi @troy-oxstreet , to troubleshoot this, we'll need to take a look at the message and Broadcast.  Please submit a request to win@customer.io with a link to the broadcast and our team will investigate.

I'll close this issue for now, but feel free to continue responding on this thread if needed.
