### ISSUE TITLE
Could you please update FirebaseMessaging and FirebaseCore dependency to the latest version?

### ISSUE THREAD

**Issue by pirrest** [customerio/customerio-ios#203]
In my project I'm using FirebaseMessaging v9.6.0 but you are 8.10.0. So I have cocoapods config.
```
[!] CocoaPods could not find compatible versions for pod "FirebaseMessaging":
  In Podfile:
    customer_io (from `.symlinks/plugins/customer_io/ios`) was resolved to 0.0.1, which depends on
      CustomerIOMessagingPushFCM (= 1.2.0-beta.3) was resolved to 1.2.0-beta.3, which depends on
        FirebaseMessaging (~> 8.10.0)

    customer_io (from `.symlinks/plugins/customer_io/ios`) was resolved to 0.0.1, which depends on
      FirebaseMessaging (~> 9.6.0)
```
Could you please update it in your .podspec file?

**Comment by ahood12** [comment]
@ami-aman OOC will you all be bumping your RN SDK to pull in the updated iOS SDK version as well? I was going through the process of integrating CIO with our app and was blocked by the out of date `FirebaseMessaging` dep. Thanks!

**Comment by ami-aman** [comment]
Hi @ahood12 
Apologies that the Firebase version is being a blocker for you. We have already added this to our list.. This might take some time as we would need to update iOS & Android SDKs first, test them and then react native package but I want to let you know that our squad is on it !  😄

**Comment by ami-aman** [comment]
Hi @ahood12 
We have already updated React native package with iOS latest stable `1.2.0`. Though, this release does not feature latest Firebase version but I want to let you know that this is on our priority list! 😄

**Comment by levibostian** [comment]
@pirrest Thank you for reporting this to us and being patient with us with getting this task completed. 

I have a branch that is available for you to install now to test that we fixed it. 

In your `Podfile`, install our SDK from git: 

```ruby
pod 'CustomerIO/MessagingPushFCM', :git => 'https://github.com/customerio/customerio-ios.git', :branch => 'levi/update-fcm'
// Note: Follow this format for all CustomerIO dependencies in your Podfile
```

We will also perform our own testing before we get a release out to you. In the meantime, see if this works in your app 😄.

**Comment by pirrest** [comment]
@levibostian Thank you for the work around for us. Waiting for the stable release.

**Comment by levibostian** [comment]
Update: We have [made a change to our iOS SDK to remove all Firebase dependencies from our SDK](https://github.com/customerio/customerio-ios/pull/210) served through cocoapods. Those of you using our SDK with Swift Package Manager are not impacted by this change as our Swift Package today already doesn't include any Firebase dependencies. 

We plan to release this change in an upcoming v2 release of the SDK. To migrate from v1 to v2 of our SDK, by us removing all Firebase dependencies from our cocoapod, you will need to make sure to install Firebase yourself in your `Podfile`:

```ruby
pod 'CustomerIO/MessagingPushFCM'
pod 'FirebaseMessaging' # <-- you will need to add this to your Podfile
```

Until v2 gets released, [the workaround](https://github.com/customerio/customerio-ios/issues/203#issuecomment-1303787347) should work for you today.
