### ISSUE TITLE
In-App Message action iOS/Android Deep Link opens preview page in Safari

### ISSUE THREAD

**Issue by Vukan-Markovic** [customerio/customerio-ios#205]
Version(s) of SDK bug appears: 1.2.0

## Current Behavior
We use _**iOS/Android Deep Link**_ action in the In-App message, but when the app is opened, and we get the in-app message, after pressing **_Yes!_** button which triggers the action, the app first opens the preview page in Safari.

## Steps to Reproduce
<img width="408" alt="Screen Shot 2022-10-14 at 1 11 01 PM" src="https://user-images.githubusercontent.com/30355243/195833362-14124928-1222-4cda-83c8-cafe8b27f7ea.png">

<img width="602" alt="Screen Shot 2022-10-14 at 1 17 32 PM" src="https://user-images.githubusercontent.com/30355243/195834570-c5ec28ac-4aa3-4499-bcba-6e37c99bc701.png">

## Expected Behavior
The app shouldn't open the preview page in Safari but should handle dynamic links in the app immediately. 

**Any other info?**
Also, we noticed some strange issue in the Customer IO console when creating an In-App message. When you try to save **_iOS/Android Deep Link_** action option for some item, it's not saved correctly, because when you refresh the page the action _**Navigate to a web page (New Tab)**_ is displayed. I'm not sure if this is somehow related to the issue described above.

We also tried to turn the option **_Skip the app preview page_** for a dynamic link that we use in the Firebase console, but it's still not working, because then it opens the link in Safari which is meant for non-mobile devices.

**Comment by Shahroz16** [comment]
Hey @Vukan-Markovic would it be possible for you to share the deep link you are testing with?

**Comment by Vukan-Markovic** [comment]
https://app.incision.care/assist/send_feedback

**Comment by Shahroz16** [comment]
Hey @Vukan-Markovic thanks for it, we tried it and it opened Incision apps directly. Can you recheck your implementation? we used iOS SDK 1.2.0

**Comment by Vukan-Markovic** [comment]
Hi @Shahroz16, thanks for checking, maybe from this video it will be more clear what issue we exactly have. So when the user taps on the **_Yes_** button in the in-app message, we want to show some feedback form. And for example, while the app is opened or in the background, when I tap on that deep link from the iOS Notes app it redirects me to the app directly and opens that feedback form, but when I tap on that **_Yes_** button in in-app message which has as action the same deep link, it first redirects me to the preview page in Safari, and then only after I click _**Open**_ on that page it returns me to the app and shows the form.

https://user-images.githubusercontent.com/30355243/196547781-fc96ce6a-4cba-46d9-bf2d-a3deb099797c.MP4

**Comment by ami-aman** [comment]
Hi @Vukan-Markovic 
Thanks for sharing the video, it really helped understand the scenario. I believe this is an expected behaviour in iOS as iOS recognises that the call is originating from your own app and should not be treated as a universal link and hence opens safari. This might make things clear :

> It’s important to understand that if your app uses [openURL:](https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl) to open a universal link to your website, the link does not open in your app. In this scenario, iOS recognizes that the call originates from your app and therefore should not be handled as a universal link by your app.
Source - https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html

This [StackOverflow question](https://stackoverflow.com/questions/46834222/how-can-i-use-universal-links-when-i-call-openurl-inside-my-own-app) can be a good reference to get the expected app behaviour. Do let us know if this helps fix the issue !

**Comment by ami-aman** [comment]
Closing the issue due to inactivity. Feel free to re-open it in case you need any help further!

**Comment by levibostian** [comment]
@vukan-markovic - You may find help to your problem [in this issue](https://github.com/customerio/customerio-ios/issues/262). Give our new release a try to see if it fixes your issue.
