### ISSUE TITLE
Event property names converted to snake case.

### ISSUE THREAD

**Issue by rabinpun** [customerio/customerio-ios#223]
JSONAdapter seems to be converting our event property names that are in camel case to snake case.

**Comment by ami-aman** [comment]
Hi @rabinpun 

Thanks for asking the question here. 

iOS SDK converts property names to snake cased before sending the data in the API request.

The class `JsonAdaptor` does follow some rules :
- All json strings must use snake_case for property names
- All Swift objects must use camelCase for it's property names

Hence, the data you are sending is converted to camel case.
However, the data sent with CustomerIO.identify("identifier", body) is not modified and is sent as is.

Is this conversion causing some trouble ? I am just curious to learn the use case/pain point here.

**Comment by rabinpun** [comment]
Hello @ami-aman. We were using a different analytics service previously and we were using camel case there. As we have a lot of customers' data with that casing we would like to still keep using it. Also, In android, customer.io sdk is not converting the camel case to snake case.

**Comment by levibostian** [comment]
Hello there, @rabinpun 

When you say, *event property names*, are you referring to the name of the tracked event or custom attributes of a tracked event? 

```swift
CustomerIO.shared.track(name: "loggedIn", data: ["ipAddress": "127.0.0.1"])
                               ^^^^^^^^ this?     ^^^^^^^^^ this? 
```

Can you share some code snippets or screenshots to help describe what data is being converted to snake case? 

Thanks!

**Comment by rabinpun** [comment]
I meant the ipAddress one. Never mind we solved it by not using the sdk altogether for sending the data from sdk. We are doing it by sending it through segment and its working fine.
