### ISSUE TITLE
No longer seeing images in rich notifications

### ISSUE THREAD

**Issue by lilidotshi** [customerio/customerio-ios#233]
**SDK version: 1.2.7** 

**Environment: Development** Development or Production

**Are logs available?: Yes** 

**Describe the bug**
We were previously able to send images with our rich push notifications and it showed up fine on 1.2.6, but since upgrading, we have not been able to see images with our rich push notifications.

Interestingly, putting a debug point on this line:
`let handled = MessagingPush.shared.didReceive(request, withContentHandler: contentHandler)`

shows that `handled` resolves to false, when previously it was resolving to true, which leads me to believe there is either an issue processing it with the new update, or the payload is incorrectly being sent now. 

Additionally, downgrading to 1.2.6 does not fix the issue.

**To Reproduce**
Enable Rich Push notifications on the app per the developer instructions
In the Rich Push Notification UI interface on Customer.io, send a test notification with an image. The test image URL I have been using is (and has been previously working for testing)
https://thumbs.dreamstime.com/b/bee-flower-27533578.jpg

More Debugging:

If i tap the notification, 

```
 let handled = MessagingPush.shared.userNotificationCenter(center, didReceive: response,
                                                                  withCompletionHandler: completionHandler)
```

returns true for handled. 

**Expected behavior**
Notification is delivered on our side with the image

**Screenshots**

**Additional context**

This is the projected payload
```
{
  "CIO": {
    "push": {
      "image": "https://thumbs.dreamstime.com/b/bee-flower-27533578.jpg"
    }
  },
  "aps": {
    "alert": {
      "title": "Hi",
      "body": "This is a test"
    },
    "mutable-content": 1
  }
}
```

This is the result of `po userInfo` in our Notification Extension
```
▿ 4 elements
  ▿ 0 : 2 elements
    ▿ key : AnyHashable("CIO-Delivery-Token")
      - value : "CIO-Delivery-Token"
    - value : <device token redacted>
  ▿ 1 : 2 elements
    ▿ key : AnyHashable("CIO")
      - value : "CIO"
    ▿ value : 1 element
      ▿ 0 : 2 elements
        - key : push
        ▿ value : 1 element
          ▿ 0 : 2 elements
            - key : image
            - value : https://thumbs.dreamstime.com/b/bee-flower-27533578.jpg
  ▿ 2 : 2 elements
    ▿ key : AnyHashable("CIO-Delivery-ID")
      - value : "CIO-Delivery-ID"
    - value : 
  ▿ 3 : 2 elements
    ▿ key : AnyHashable("aps")
      - value : "aps"
    ▿ value : 2 elements
      ▿ 0 : 2 elements
        - key : alert
        ▿ value : 2 elements
          ▿ 0 : 2 elements
            - key : title
            - value : Hi
          ▿ 1 : 2 elements
            - key : body
            - value : This is a test
      ▿ 1 : 2 elements
        - key : mutable-content
        - value : 1
```

**Comment by lilidotshi** [comment]
Updated: Needed to initialize Customer.io in the service extension as well per new docs.

**Comment by levibostian** [comment]
Glad that you noticed the recently updated docs, @lilidotshi! Hope they help you. 

Contact us again if they are unclear. Docs are a big initiative of ours especially at the moment so we would love to help you out with them when we can.
