### ISSUE TITLE
Deep links are not working for 2.0.0 when the app has been closed.

### ISSUE THREAD

**Issue by vadimux** [customerio/customerio-ios#235]
**SDK version:** 2.0.0

**Environment:** Development and Production

**Are logs available?** 
No, due to the app is closed

**Describe the bug**
Precondition: The app was closed ("killed"). When a user receives a rich push notification that contains a deep link and he taps on it, the user is not redirected to the target screen (based on a deep link), the user is just on the first screen of the app. 
When the app is in foreground/background - the rich push notification with deep link works as expected.

**To Reproduce**
Enable Rich Push notifications on the app per the developer instructions
Kill the app
In the Rich Push Notification UI interface on Customer.io, send a test notification with a deep link.

**Expected behavior**
the user is redirected by deep link correctly

**Screenshots**
no

**Additional context**
I've checked the same behavior for [1.2.7](https://github.com/customerio/customerio-ios/releases/tag/1.2.7) - it works as expected when the app was killed. It means when the user taps on rich push notification with deep link the user is redirected to the target screen without any issues.

`{
  "CIO": {
    "push": {
      "link": "myscheme://il/testclient/mymail",
    }
  },
  "aps": {
    "mutable-content": 1,
    "alert": {
      "title": "Message!",
      "body": "Open it!"
    }
  }
}`

**Comment by ami-aman** [comment]
Hi @vadimux 

Appreciate you bringing this to our attention. I am trying to reproduce this issue on our sample app using iOS SDK version 2.0.0 but it seem to be working fine. Is there anything you would like to add that can help us reproduce ?

**Comment by vadimux** [comment]
Hi @ami-aman,

thank you for reply, I've investigated this behaviour deeper and, as I see, when the rich push notification appears (SDK 2.0.0) and user taps on it - the app launches, but method `- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options API_AVAILABLE(ios(9.0)); ` has never called. 

I've checked with SDK 1.2.7 and this method is triggered when user taps on rich push notification (before this the app should be killed)

migration should be correct, because there is one issue with deep links only for the killed app. In foreground/background state it works as expected.

thanks

**Comment by levibostian** [comment]
Thanks for sending us more details. It's greatly appreciated. 

I have done some of my own debugging and have not yet been able to reproduce the issue that you are having. 

Following the steps suggested:
* Setup app for rich push. 
* Kill app.
* In rich push composer in Customer.io, send a test notification with a deep link

Through my testing, I have been able to successfully use deep linking within my iOS app. 

I have a few suggestions that I can think of until we are able to reproduce the issue. 
1. Is your app setting up a [a notification center delegate](https://github.com/customerio/RemoteHabits-iOS/blob/d2c15aac3f4d73bfd65980c2ddb6e1a0f5f6302e/Remote%20Habits/AppDelegate.swift#L20) and [calling the Customer.io SDK when a notification is interacted with in the delegate](https://github.com/customerio/RemoteHabits-iOS/blob/d2c15aac3f4d73bfd65980c2ddb6e1a0f5f6302e/Remote%20Habits/AppDelegate.swift#L72-L83)?
2. Are you using Scene delegates in your app? UIKit? SwiftUI? Depending on what tech you're using, deep links will call different methods in your app. For example, in the testing app I am using, the App Delegate function `application(openURL:)` doesn't get called. Instead, a function in [my Scene delegate](https://github.com/customerio/RemoteHabits-iOS/blob/d2c15aac3f4d73bfd65980c2ddb6e1a0f5f6302e/Remote%20Habits/SceneDelegate.swift#L51) does. 

Sorry we are not able to reproduce the issue yet. I hope these suggestions give some insight that's helpful to getting this issue resolved for you.

**Comment by vadimux** [comment]
Thanks for you proposals, @levibostian 

I'd like to clarify the steps:
1. use 1.2.7 CIO iOS SDK
2. Setup app for rich push.
3. Kill app.
4. In rich push composer in Customer.io, send a test notification with a deep link - a deep link works as expected
5. pod update CustomerIO (use 2.0.0)
6. update initialisation of SDK in code (need to add region and optional config)
7. repeat steps 3,4 - deep link isn't handled
8. if downgrade to 1.2.7 - again it works as expected

about you questions:

1. yes, it works within Notification center delegate
2. we use UIKit and Objc+Swift and we have only one enter point for deep link and universal link- `(BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options API_AVAILABLE(ios(9.0));`

**Comment by levibostian** [comment]
Thanks for sending that info. 

Sorry that you're experiencing this issue. We want you to be able to upgrade to v2. It's a great release! 

I think we need to collect some more information to help debug this situation for you. I am still not sure why this is happening to you? I have a few ideas that I'm discussing with the team to decide the best approach. I'll get back to you with our decision. 

This project is still pretty young and we appreciate people like yourself working with us to find places in the product we can improve. This includes debugging issues!

**Comment by levibostian** [comment]
@vadimux, I created a new branch in this project named `levi/deep-links-debugging` that adds more logging specifically to help us debug this issue you're having with deep links. 

I do *not* suggest that you ship your app to production with this build of our SDK. Instead, I would appreciate if you install this SDK build into a development build of your app, go through the reproducing steps you have shared to reproduce the issue, then send us the logs that you receive. 

I have some docs here to help you complete these steps. 
* [Install a build of our SDK from a git branch](https://github.com/customerio/customerio-ios/blob/levi/support-doc/docs/SUPPORT.md#install-build-of-sdk-from-a-git-branch)
* [Capture SDK logs](https://github.com/customerio/customerio-ios/blob/levi/support-doc/docs/SUPPORT.md#how-to-capture-logs-from-sdk-to-send-to-customerio-team) to send to our team. 

So, when you get a chance, please capture these logs and send them my way so I can take a look. 

> Note: The docs above and the git branch are all drafts and a work in progress. You may encounter issues with these. Please, share your issues so we can make them better before shipping 😄.

**Comment by vadimux** [comment]
@levibostian thank you for this detail. One question - we use `MessagingPushAPN`, but I see `CustomerIOMessagingPushFCM` - should I use FCM instead of APN? If "yes", I should rewrite code and we don't have fcm token as well, if I should use APN (`pod 'CustomerIOMessagingPushAPN', :git => 'https://github.com/customerio/customerio-ios.git', :branch => branch_name`) I can't compile project. Could you please clarify?

**Comment by levibostian** [comment]
Sorry about that confusion. 

If you use APN, install pod `CustomerIOMessagingPushAPN`. If you use FCM, install pod `CustomerIOMessagingPushFCM`. So for you, continue to use APN - no ask for you to switch to using FCM. 

If you use this in your Podfile:

```
branch_name = 'levi/deep-links-debugging'
pod 'CustomerIOCommon', :git => 'https://github.com/customerio/customerio-ios.git', :branch => branch_name
pod 'CustomerIOMessagingPush', :git => 'https://github.com/customerio/customerio-ios.git', :branch => branch_name
pod 'CustomerIOTracking', :git => 'https://github.com/customerio/customerio-ios.git', :branch => branch_name
pod 'CustomerIOMessagingPushAPN', :git => 'https://github.com/customerio/customerio-ios.git', :branch => branch_name
```

run `pod update` and you get compile errors, could you send those compile errors my way?

**Comment by vadimux** [comment]
@levibostian thank you and I've provided logs (for foreground and background states) to support team at win@customer.io
