### ISSUE TITLE
Crash in 1.2.8, MessagingInApp

### ISSUE THREAD

**Issue by lilidotshi** [customerio/customerio-ios#242]
**SDK version:** 
1.2.8

**Environment:** Development or Production
Production

**Are logs available?** 

```
CioMessagingInApp/MessagingInApp.swift:21: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
CioMessagingInApp/MessagingInApp.swift:21: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
```

**Describe the bug**

Upgraded from 1.2.7 to 1.2.8, and am seeing a crash when initializing the logger.debug. In particular `DIGraph.getInstance(siteId: siteId)` is returning nil and throwing the error

**To Reproduce**

Upgrade to 1.2.8
Turn on debug logging
Start app and hit the debug logging

**Expected behavior**

Initialization should work

**Screenshots**

No screenshot but stack trace is
```
#4	0x0000000106047e34 in MessagingInApp.diGraph.getter at SourcePackages/checkouts/customerio-ios/Sources/MessagingInApp/MessagingInApp.swift:21
#5	0x0000000106047f1c in MessagingInApp.logger.getter at SourcePackages/checkouts/customerio-ios/Sources/MessagingInApp/MessagingInApp.swift:33
#6	0x000000010604836c in MessagingInApp.initialize(organizationId:) at SourcePackages/checkouts/customerio-ios/Sources/MessagingInApp/MessagingInApp.swift:61
```

**Additional context**

**Comment by levibostian** [comment]
Thank you for reporting this issue, @lilidotshi. I appreciate it. 

Looking through the stacktrace that you sent (thank you!), this does indeed look like a crash could happen. 

I do have 2 ideas for you to try:
* Can you make sure that every place in your code where you are calling `MessagingInApp.initialize(organizationId: )`, you are calling `CustomerIO.initialize()` before? `MessagingInApp.initialize` is assumed that it's being called after `CustomerIO.initialize`. 
* v2 of the iOS SDK has been released. v2 includes some architecture changes to the code which should eliminate this bug from happening all together. [See our migration doc](https://customer.io/docs/sdk/ios/migrate-upgrade/) to help you migrate to this backwards compatible release of our SDK.

**Comment by levibostian** [comment]
Thanks for confirming that for me. 

I believe I have enough information to reproduce this issue. I will take it from here and get back to you when I have an update. 

In the meantime, I believe version `1.2.7` should not have this bug. Try it out to see if it works while I work on resolving this issue for you.

**Comment by lilidotshi** [comment]
Thanks @levibostian! I can confirm 1.2.7 works currently

**Comment by levibostian** [comment]
Version 1.2.9 has been released! 

Install it and see if this resolves your issue, @lilidotshi. 

I'm going to close this issue for now assuming it's fixed. We can re-open it if you still experience problems.
