### ISSUE TITLE
[Feature Request] Add a new function to InAppEventListener that would allow customization of message action

### ISSUE THREAD

**Issue by glauberl-ciandt** [customerio/customerio-ios#312]
I have the same issue reported in https://github.com/customerio/customerio-ios/issues/205, which is Universal Links when triggered from In-App won't open the app but the system's browser - and I completely understood the technical reasons behind this, as explained there.

That said, I thought about an option that would allow the message action event to be intercepted and then customized if needed.

My suggestion to address this is to add a new method to the `InAppEventListener` delegate - **messageActionWillExecute**, like this:

```swift
public func messageActionWillExecute(message: CioMessagingInApp.InAppMessage, actionValue: String, actionName: String) -> Bool {
    // Having this delegate method would allow message to be inspected beforehand then we could choose to:
    // - Let it continue,
    // - Cancel its execution, 
    // - Or perform some customized action

    // Returning true -> The message action will execute
    // Returning false -> The message action won't execute
}
```

And example usage scenario: processing universal links from In-App:
```swift
public func messageActionWillExecute(message: CioMessagingInApp.InAppMessage, actionValue: String, actionName: String) -> Bool {
    // Run a custom deep linking handling mechanism, cancelling default message action behavior
    if let url = URL(string: actionValue) {
        aCustomDeepLinkingHandlerInstance.handle(url: url)
        return false
    }

    // Resume with the default message action behavior
    return true
}
```

Let me know if you need additional information.

**Comment by Shahroz16** [comment]
Hey @glauberl-ciandt, thank you for writing to us and for a great proposal. We are currently evaluating our options to me the `universal-link` experience smoother for in-app messages. It's on our near roadmap and we hope to send something out soon. Thank you for your patience and proposal.

**Comment by Shahroz16** [comment]
Hey @glauberl-ciandt, thank you for being very patient with us while we worked on this. I have good news for you and everyone who asked for it. 

We have released the support for universal links from in-app, you can find more details about it [here](https://www.customer.io/docs/sdk/ios/in-app/#universal-links-deep-links).  

Feel free to re-open this, in-case you encounter any issues.
