### ISSUE TITLE
Rich push notifications not showing media files with APNS.

### ISSUE THREAD

**Issue by prema-banknovo** [customerio/customerio-ios#337]
Rich push notification is working with APNS
I have followed the documentation provided: [here](https://customer.io/docs/sdk/ios/push/#rich-push)

**SDK version:** 2.6.1

**Describe the issue**
 Rich push notification is not showing media file with APNS integration only contents are visible like normal notifications.
 
 Added UNNotificationServiceExtension

 ```
 Import UserNotifications
 import CioMessagingPushAPN
 import CioTracking

class NotificationService: UNNotificationServiceExtension {
     
override func didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
    CustomerIO.initialize(siteId: CustomerIOEnvironment.customerIOSiteId, apiKey: CustomerIOEnvironment.customerIOApiKey, region: Region.US) { config in
       config.autoTrackPushEvents = true
    }
    MessagingPush.shared.didReceive(request, withContentHandler: contentHandler)
 }
    
 override func serviceExtensionTimeWillExpire() {
    MessagingPush.shared.serviceExtensionTimeWillExpire()
  }
}
```

**Screenshots**
Payload  - 

<img width="576" alt="Screenshot 2023-06-22 at 10 53 54 AM" src="https://github.com/customerio/customerio-ios/assets/91462087/6b9015e4-81dc-4ee6-a0ab-61f0839cff38">

Notification view without image - 

![IMG_4219](https://github.com/customerio/customerio-ios/assets/91462087/2e9e0d0f-dab2-4313-b687-669f4d4ad1fb)

Team - Can you please help me here to identify the issue ?

Thanks

**Comment by mrehan27** [comment]
Hi @prema-banknovo. To assist you in resolving this matter, we kindly request the following information:

1. Could you please confirm if you have embedded the `NotificationServiceExtension` in your application as [suggested in Step 3](https://customer.io/docs/sdk/react-native/push/#ios-rich-push-prerequisites) of our documentation?
2. Have you correctly set the deployment target for your iOS application? If the device you are testing on has an iOS version lower than the deployment target, the `NotificationServiceExtension` may not be connected to the main target, and rich push functionality may not work as expected.
3. Can you try using a different image and ensure that it follows the [requirements mentioned in our documentation](https://customer.io/docs/sdk/ios/troubleshooting/#image-display-issues)?
4. Please [capture logs from the SDK](https://customer.io/docs/sdk/ios/troubleshooting/#capture-logs) to identify any error messages or unusual behavior, and kindly share them with us. Before sharing the logs, please ensure that any sensitive data has been removed.

Thank you for your cooperation, and please don't hesitate to reach out if you have any further inquiries or concerns.

**Comment by prema-banknovo** [comment]
@mrehan27 - 
I have tried all the steps mentioned above still no luck.

Please find the details -
 - model - iPhone 13 mini , OS - 16.0.2
 - deeplink behaviour is - first  launching the App and after login  redirecting to browser when I am redirecting to App then it showing correct screen.

**Comment by lj-cio** [comment]
Hi @prema-banknovo, stepping in for @mrehan27 here to help get this resolved.  

To help make sure we're not missing anything outside of the implementation itself, please send the logs that you captured to [win@customer.io](mailto:win@customer.io) along with a link to the message in Customer.io that you're using to test. With that information, we'll be able to take a closer look at your setup using the Activity Logs in your workspace.

I'm going to go ahead and close the issue here and look out for your email, but please re-open if you have issues with sending the information to the support email.
