### ISSUE TITLE
External libraries are being added with the latest SDK version.

### ISSUE THREAD

**Issue by mplanckensteiner** [customerio/customerio-ios#371]
New external libraries are being added with the latest SDK version using SPM. 

**SDK version:**  2.7.8

**Describe the issue**

I am wondering if this is expected that all the versions after 2.6.1 are by default including FCM. Haven't found any notes regarding this so I would appreciate it if you could provide more context. Or if there is any way to avoid adding FCM when is not needed.

**Screenshots**

<img width="288" alt="Screenshot 2023-08-15 at 15 20 39" src="https://github.com/customerio/customerio-ios/assets/49713385/3d4bb4c8-d623-4d36-9280-6fef54fdccd6">

Thanks

**Comment by levibostian** [comment]
Great question, @mplanckensteiner. 

You are correct in that [in version `2.7.0`, the FCM SDK was added as a dependency of the Customer.io iOS SDK](https://github.com/customerio/customerio-ios/releases/tag/2.7.0) to make installing and using our SDK easier. 

SPM's current behavior is to download all dependencies for a given package, even if your app does not need a target that requires that dependency. This is why you are seeing this behavior of FCM's SDK being downloaded in Xcode, even if you are not using the `MessagingPushFCM` library. 

The SPM team [plans on improving this behavior](https://github.com/apple/swift-package-manager/issues/4759) in the future. Although Xcode does download the FCM SDK to your computer, the FCM SDK is not installed in your iOS app unless you use the `MessagingPushFCM` Customer.io SDK target. 

I hope this answers your question. Have an awesome day!
