### ISSUE TITLE
[Feature] iOS Privacy Manifest Support

### ISSUE THREAD

**Issue by GaeCuure** [customerio/customerio-ios#646]
Apple announced that all SDK providers are required to supply a privacy manifest if the SDK uses one of the APIs listed here [privacy manifest docs](https://developer.apple.com/documentation/bundleresources/information_property_list). After a quick scan, I noticed that this library is using some UserDefaults API so it would require a privacy manifest file. I would be glad to do it but my knowledge of pods configuration and Swift is limited

```
./ios/Pods/CustomerIOCommon/Sources/Common/Util/KeyValueStorage.swift: Uses UserDefaults to store data in key/value pairs.
./ios/Pods/CustomerIOCommon/Sources/Common/Util/KeyValueStorage.swift:    private var userDefaults: UserDefaults? {
./ios/Pods/CustomerIOCommon/Sources/Common/Util/KeyValueStorage.swift:        UserDefaults(suiteName: getFileName()) 
```

**Comment by levibostian** [comment]
Hello, @GaeCuure. Thanks for asking about this. 

We are aware of these new requirements and we have documented it internally. We will continue monitoring this requirement and prioritize it in our SDK accordingly. 

I hope you have a fantastic day. Thanks again for asking about this.

**Comment by levibostian** [comment]
Update: As shared [in a related issue](https://github.com/customerio/customerio-reactnative/issues/248#issuecomment-2025900907), this task is being actively worked on during our current development cycle. Matter of validating the manifest from the relevant stakeholders to ensure we got it covered right before publishing it.

**Comment by levibostian** [comment]
This has been shipped today. 

Install either [3.1.0](https://github.com/customerio/customerio-ios/releases/tag/3.1.0) or [2.13.0](https://github.com/customerio/customerio-ios/releases/tag/2.13.0) in your app. Give it a try and let us know if you encounter problems along the way.
