### ISSUE TITLE
Conflict with analytics-swift (Segment)

### ISSUE THREAD

**Issue by qwer10023500** [customerio/customerio-ios#670]
![90128368-78FA-4F3C-AD62-2A414FFD4F88](https://uploads.linear.app/1c4bbdb0-d726-4ea2-9b9b-90a5adcc2827/642111ef-d830-48d3-9209-c92cdeb34af9/e81cc7bc-fdb3-470a-a87d-d6244b92bea2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzFjNGJiZGIwLWQ3MjYtNGVhMi05YjliLTkwYTVhZGNjMjgyNy82NDIxMTFlZi1kODMwLTQ4ZDMtOTIwOS1jOTJjZGViMzRhZjkvZTgxY2M3YmMtZmRiMy00NzBhLWE4N2QtZDYyNDRiOTJiZWEyIiwiaWF0IjoxNzExMzQ5Nzc4LCJleHAiOjMzMjgxOTA5Nzc4fQ.QqjZbdZl1wqH6sW0e5nvI-OnFNdkww94wwOk5Y3-zek "=1440x")

![WX20240325-142303@2x](https://uploads.linear.app/1c4bbdb0-d726-4ea2-9b9b-90a5adcc2827/65642c31-e9ee-45cc-bd9b-01d62761a5c3/e8728683-b687-4269-aa35-a5388031a5c2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzFjNGJiZGIwLWQ3MjYtNGVhMi05YjliLTkwYTVhZGNjMjgyNy82NTY0MmMzMS1lOWVlLTQ1Y2MtYmQ5Yi0wMWQ2Mjc2MWE1YzMvZTg3Mjg2ODMtYjY4Ny00MjY5LWFhMzUtYTUzODgwMzFhNWMyIiwiaWF0IjoxNzExMzQ5Nzc4LCJleHAiOjMzMjgxOTA5Nzc4fQ.o9YZPpd46a8AHurXSuq8JciZ1JrMCpdgp5eMSMShhSg)

**Comment by Shahroz16** [comment]
Hey @qwer10023500, thank you for reaching out. This is correct, the customer.io iOS SDK is using Segment SDK. 

Can you please share your usecase, why do you need both the SDKs?

**Comment by qwer10023500** [comment]
We use customerio in our project, and also use segment to forward to other platforms such as firebase.

**Comment by qwer10023500** [comment]
<img width="374" alt="image" src="https://github.com/customerio/customerio-ios/assets/15137068/c83fc9cd-35c4-4bbb-a066-63b40496632e">

https://github.com/segmentio/analytics-swift

Analytics-swift and customerio-ios cannot be integrated at the same time

**Comment by Shahroz16** [comment]
Ideally you should just need on CDP. I would love to talk more about your usecase and see what we can do here. 

Are you using destination plugin for firebase? Or it a destination?

**Comment by qwer10023500** [comment]
https://github.com/segment-integrations/analytics-swift-firebase

**Comment by qwer10023500** [comment]
Yes, we use segment Supported Device Mode Destinations

https://github.com/segmentio/analytics-swift?tab=readme-ov-file#supported-device-mode-destinations

**Comment by Shahroz16** [comment]
@qwer10023500 Excellent thanks for the information, I think it should work with Customer.io SDK as well. 

Once you add the dependency, 

```
.package(
            name: "Segment",
            url: "https://github.com/segment-integrations/analytics-swift-firebase.git",
            from: "1.1.3"
        ),
```

initialize the SDK,

```
 let config = SDKConfigBuilder(cdpApiKey: "YOUR_CDP_API_KEY")
         .migrationSiteId(YOUR_SITE_ID)
         .autoTrackDeviceAttributes(true)

     CustomerIO.initialize(withConfig: config.build())
     CustomerIO.add(plugin: FirebaseDestination())
```

Can you please try that and let me know?

**Comment by Shahroz16** [comment]
Alright, so I see, `https://github.com/segment-integrations/analytics-swift-firebase.git` is brining in the dependency as well which is causing the conflict, let me see how we can fix it and get back to you, thanks for working with me here on this :)

**Comment by qwer10023500** [comment]
okay, thank you

**Comment by Shahroz16** [comment]
@qwer10023500 thank you for your patience here, would you be willing to give this package a shot?

https://github.com/customerio/cdp-analytics-swift-firebase

just add this dependency to your project, and then add the plugin, code in ReadMe as well

```
import CioDataPipelines
import SegmentFirebase // <-- Add this line

 // Configure and initialize the Customer.io SDK
  let config = SDKConfigBuilder(cdpApiKey: "cdpApiKey")
 CustomerIO.initialize(withConfig: config.build())
        
 CustomerIO.shared.add(plugin: FirebaseDestination())
```

Let me know if you face any issue while getting it to work, I'll be keeping an eye out for your message.

**Comment by qwer10023500** [comment]
Sorry, my boss thinks this is wrong and he will contact you guys via support later.

**Comment by qwer10023500** [comment]
If you do this you must support all of the following platforms
![WX20240326-104215@2x](https://github.com/customerio/customerio-ios/assets/15137068/80524635-82e0-4a55-b7d6-af24e7e3de1a)

**Comment by scotttwittrockcio** [comment]
@qwer10023500 Thanks for sharing that additional information. We'll keep looking into ways to utilize both the segment SDK and customer-io SDK. Is this a full list of device mode destinations you are utilizing? We don't currently support device mode destinations on our mobile SDK, but trying to capture interest in the various destinations.

**Comment by qwer10023500** [comment]
I am using Swift Package Manager to manage third-party tools. I found that after integrating CustomerIO and analytics-swift at the same time, the program cannot be run. By observing, I found that the following content in Package.swift in CustomerIO caused the problem.
![WX20240326-111423@2x](https://github.com/customerio/customerio-ios/assets/15137068/1c036dd0-d542-46a9-bac6-941000fc7a24)
Can you guys try to modify it?

**Comment by qwer10023500** [comment]
I think changing the url to "https://github.com/segmentio/analytics-swift.git" can solve this problem

**Comment by qwer10023500** [comment]
Can refer to
https://github.com/segment-integrations/analytics-swift-firebase/blob/main/Package.swift

**Comment by qwer10023500** [comment]
Our project contains Supported Device Mode Destinations

Amplitude
AppsFlyer
Facebook
Firebase
Customer IO

Therefore I need to add dependencies through segment instead of Customer IO

**Comment by Ahmed-CIO** [comment]
@qwer10023500 thank you for your patience and all the details provided. We are looking into this to provide either a solution or a simple feasible work around till we build a more long term solution.

**Comment by Ahmed-CIO** [comment]
Hi @qwer10023500 thanks again for your patience while we are trying to find a resolution. For the time being if you need to use Segment side by side with our iOS SDK, the best option is to use our latest iOS SDK 2.x instead of 3.x.
We are committed to support SDK 2.x till the SDK 3.x works smoothly in scenario like yours.

I will also communicate with our TS team to help your team for any relevant follow ups with this one.

**Comment by darryljohnson** [comment]
Hey team, I want to callout that this affecting [our app](https://apps.apple.com/us/app/bezel-authenticated-watches/id1586195658) as well. We use CustomerIO for messaging and Segment as our CDP. For the time being we'll remain on 2.x until you all are able to support 3.x side-by-side with direct Segment usage.

**Comment by Shahroz16** [comment]
Hey @darryljohnson, thanks for reaching out and it's noted. We are working on it, appreciate your patience here.

**Comment by matthewkertis** [comment]
We are also seeing issues when trying to integrate 3.1.0 while using [Analytics-iOS](https://github.com/segmentio/analytics-ios). We noticed this was closed and marked as `unplanned`, is there a current fix for this somewhere or an ETA on when one is expected?

**Comment by scotttwittrockcio** [comment]
Hi @matthewkertis, thanks for your feedback. Are you looking to run both the CIO SDK and Analytic-iOS SDK in your app or are you transitioning over? We are evaluating the effort to be able to support running both in parallel. We just haven't locked in a clear solution yet. 

In the meantime, we do offer a lot of the same functionality as the Analytics-iOS SDK so you _might_ be able to use our SDK only. I'd love to hear more about your use case. If it's easier to share privately you can email product@customer.io to start a thread with me.

**Comment by PaulWen** [comment]
Hi @scotttwittrockcio, I am also running into the same issue. Currently, we use Segment for tracking app events and only have the CIO SDK in place for rich push notifications and in-app messages. The main reason for updating to 3x is the privacy manifest added in 3.1.0.

(CC: @Shahroz16)

**Comment by Shahroz16** [comment]
Hey @PaulWen, thanks for more details, the privacy manifest is[ added in 2.x as well.  ](https://github.com/customerio/customerio-ios/releases/tag/2.13.0)

**Comment by Ahmed-Ali** [comment]
I am happy to share with you that from the release 3.2, we expect Segment to work just fine side by side with our SDK
