### ISSUE TITLE
DataPipelines crash

### ISSUE THREAD

**Issue by alpha-moisol** [customerio/customerio-ios#698]
**SDK version:** 3.0.1

**Environment:** Production

**Describe the bug**
Got some crashes in production

**Additional context**

```
Crashed: com.apple.root.background-qos
0  [Reducted]                     0x6be390 closure #1 in DataPipelineMigrationAssistant.handleQueueBacklog(siteId:) + 62 (DataPipelineMigrationAssistant.swift:62)
1  [Reducted]                     0x68a618 thunk for @escaping @callee_guaranteed () -> () + 4317652504
2  libdispatch.dylib              0x24b4 _dispatch_call_block_and_release + 32
3  libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
4  libdispatch.dylib              0x15b8c _dispatch_root_queue_drain + 684
5  libdispatch.dylib              0x16284 _dispatch_worker_thread2 + 164
6  libsystem_pthread.dylib        0xdbc _pthread_wqthread + 228
7  libsystem_pthread.dylib        0xb98 start_wqthread + 8
```

**Comment by levibostian** [comment]
Thanks for sending this to us, Andrii. Sorry that you experienced this. 

Unfortunately, the stacktrace isn't enough information for us to reproduce the issue and get it resolved. To help us reproduce this issue, could you answer these questions to provide us with more context? 

* If you're able to reproduce this crash in your app, what steps do you perform in your app to trigger this crash? 
* Is this happening for all of your app users or only some? 
* What line of code is called last in your app before you see this crash occur? We would appreciate if you send us this code block. 
* Is this a new behavior you're seeing or has it always been happening? What version is this crash happening for and what versions is it not happening for? 
* Were you using a previous version of our SDK before 3.0.1? If so, what version? 

Any other context that would help us reproduce this issue would be greatly appreciated. 

It's understandable that some of these answers have sensitive information inside of it. Feel free to send those answers to `win@customer.io` and in the email, link to this github issue. The team will route the message appropriately when they receive it.

**Comment by alpha-moisol** [comment]
@levibostian We were not able to reproduce the crash, it happens only for 2 user so far, but 13 times already. Seems to crash at the start of the app (didFinishLaunchingWithOptions just get called, in which there is initialization of CustomerIO). We just migrated from 2.x.x to 3.0.1.

**Comment by levibostian** [comment]
The stacktrace you sent in the description, is that the complete stacktrace you received? Could you send the complete stacktrace if there is more? 

Any additional context you could share, even if you believe it might not be helpful, would be great. Unfortunately, with the information provided thus far, I am not able to reproduce it.

**Comment by alpha-moisol** [comment]
> The stacktrace you sent in the description, is that the complete stacktrace you received? Could you send the complete stacktrace if there is more? 
> 
> 
> 
> Any additional context you could share, even if you believe it might not be helpful, would be great. Unfortunately, with the information provided thus far, I am not able to reproduce it. 

This is only stack trace we received from Firebase Crashlytics.

**Comment by alpha-moisol** [comment]
It seems there is some optional unwrap

**Comment by levibostian** [comment]
> It seems there is some optional unwrap

Would you be able to provide some information for this?

**Comment by alpha-moisol** [comment]
@levibostian 
![CleanShot 2024-04-12 at 20 21 34@2x](https://github.com/customerio/customerio-ios/assets/133892736/5064ad3d-0e87-4958-8f6a-0602013a4bce)
This line specifically.

**Comment by levibostian** [comment]
Thank you for providing that information. Very helpful. 

Our team is looking into this and trying to reproduce it internally. 

While we do this, could you provide the steps that you took to trigger this line of code? This could help expedite the process with reproducing it and fixing the issue. 

Sorry again that you experienced this. Thank you for answering my questions to get this resolved.

**Comment by alpha-moisol** [comment]
> Thank you for providing that information. Very helpful. 
> 
> 
> 
> Our team is looking into this and trying to reproduce it internally. 
> 
> 
> 
> While we do this, could you provide the steps that you took to trigger this line of code? This could help expedite the process with reproducing it and fixing the issue. 
> 
> 
> 
> Sorry again that you experienced this. Thank you for answering my questions to get this resolved. 

Unfortunately, could not reproduce it locally ourselves, this is stack trace from our user on production

**Comment by alpha-moisol** [comment]
The issue is spreading, but we noticed that all crashes occur on iOS 17.2.1

**Comment by alpha-moisol** [comment]
Seems like `attributesJsonString` is nil, so it should be check on this line before force unwrapping it

**Comment by levibostian** [comment]
While I am not able to provide a date on when to expect a fix to become available, I will mention our team is actively working on this issue and plan to ship it as soon as we can. 

Thanks again for working with us to get this issue resolved. I will update this issue with the status as it changes.

**Comment by levibostian** [comment]
Version `3.1.2` of the Customer.io iOS SDK has been deployed and ready to install. This release includes a bug fix to resolve this crash. 

Thank you again for reporting this to us and working with us to get it resolved. Sorry that you experienced this crash. We hope `3.1.2` is successful for you. If not, please reach out again.
