### ISSUE TITLE
Push Token is not setting to the User

### ISSUE THREAD

**Issue by alpha-sagar** [customerio/customerio-ios#711]
Written Code as per the documentation like below 

`let config = SDKConfigBuilder(cdpApiKey: customerAPIKey)
                   .autoTrackDeviceAttributes(true)
                   .migrationSiteId(customerSiteID) // only required for migration
               CustomerIO.initialize(withConfig: config.build())
               let autoScreenTrack = true
               if autoScreenTrack {
                   CustomerIO.shared.add(plugin: AutoTrackingScreenViews(filterAutoScreenViewEvents: nil, autoScreenViewBody: nil))
               }
               // Initialize messaging features after initializing Customer.io SDK
               MessagingInApp
                   .initialize(withConfig: MessagingInAppConfigBuilder(siteId: customerSiteID, region: .US).build())
                   .setEventListener(self)
               MessagingPushAPN.initialize(
                   withConfig: MessagingPushConfigBuilder()
                       .autoFetchDeviceToken(true)
                       .autoTrackPushEvents(true)
                       .showPushAppInForeground(true)
                       .build()
               )`

also setting the Profile and token as follows :
`func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        print("Successfully registered for notifications!")
        let pushTokenString = deviceToken.reduce("", {$0 + String(format: "%02X", $1)})
        print("APNs device token: \(pushTokenString)")
        CustomerIO.shared.registerDeviceToken(pushTokenString)
        MessagingPush.shared.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
    }`
and
`let body = [
            mxFirstName:loggedInUser.firstName,
            mxLastName:loggedInUser.lastName,
            emailAddressCIO:loggedInUser.email,
            User_Local.relationship:loggedInUser.relationship,
            User_Local.roleType:loggedInUser.role,
            accountIDCIO:loggedInUser.adminID,
            "timezone": localTimeZoneIdentifier
        ]
        CustomerIO.shared.identify(userId: loggedInUserID, traits: body)
        if pushTokenString != "" { CustomerIO.shared.registerDeviceToken(pushTokenString) }`
        
      we are able to capture the token ; Still its not registering the device!
      
      What may be going wrong here ?

**SDK version:**  3.1.2

Help will be appreciated !

Thanks.

**Comment by alpha-sagar** [comment]
@Shahroz16 
Thanks for replying !
I tried but no luck that why I tried using
`.autoFetchDeviceToken(false)`
and its redirected to 
`func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data)` 
method properly But 
`MessagingPush.shared.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)`
 this is not seeting device token properly.

Logs - [LoggerFile.txt](https://github.com/customerio/customerio-ios/files/15107236/LoggerFile.txt)

Thanks

**Comment by Shahroz16** [comment]
@alpha-sagar, can you please recheck the CDP API key you are adding? please note its different from the tracking API key that you were using before. You will find[ this in your data pipeline sources.](https://customer.io/docs/sdk/ios/quick-start-guide/#prerequisites)


If this doesn't resolve the issue, to help make sure we're not missing anything outside of the implementation itself, please send the logs that you captured to [win@customer.io](mailto:win@customer.io). We'll be able to take a closer look at your setup using the Activity Logs/ Data Pipeline sources in your workspace.

**Comment by alpha-sagar** [comment]
That was the pipeline issue.
We didn't connected Piperline source to its destination.
now its working !
