### ISSUE TITLE
Application: UIApplication, continue userActivity called twice when autoTrackPushEvents is set to true

### ISSUE THREAD

**Issue by dandreiolteanu** [customerio/customerio-ios#715]
**SDK version:**  3.2.0

**Environment:** Development + Production

**Describe the bug**

Letting Customer.io to handle deeplinks while also having `autoTrackPushEvents` set tot true will cause the `continue userActivity` method from AppDelegate to be called twice. I think that it happens due to swizzling and you call `handleDeeplink` from 2 places ⬇️
 
![CleanShot 2024-05-17 at 19 21 12@2x](https://github.com/customerio/customerio-ios/assets/26720542/07eefccf-8296-4699-92ea-4b099966e6c2)
![CleanShot 2024-05-17 at 19 20 38@2x](https://github.com/customerio/customerio-ios/assets/26720542/5b568be8-a0a2-42fc-9e08-88c210e3b08b)

**Expected behavior**

the `continue userActivity` method from AppDelegate should be called only once.

Thanks!

**Comment by levibostian** [comment]
Hello there, Andrei. Thanks for contacting us today. 

Could you give describe your code up to the point where these breakpoints are being triggered? Code snippets are ideal to share. 

The `onPushAction` function is meant to be called automatically when the `autoTrackPushEvents` config option is `true`. the `manualPushClick` function is meant to be called when your app manually calls `MessagingPush.userNotificationCenter(didReceive:)`. 

Could you check your code to see if you're calling `MessagingPush.userNotificationCenter(didReceive:)`? If so, you can go ahead and delete that code [as mentioned here](https://customer.io/docs/sdk/ios/2.x/update-210-to-211/#upgrade-2.10). 

Have a great day!
