### ISSUE TITLE
3.x.x migration leads to crash in CioAnalytics 

### ISSUE THREAD

**Issue by rajAppmetry** [customerio/customerio-ios#721]
**SDK version:** 3.2.0

**Environment:** Development and Production

**Describe the bug**
We are trying to migrate from 2.x.x to the latest version and it is crashing in analytics while initiating WKWebview.

**To Reproduce**
Just initialising the customer io and opening the app crashing the app

**Screenshots**

![Screenshot 2024-05-20 at 11 13 59 AM](https://uploads.linear.app/1c4bbdb0-d726-4ea2-9b9b-90a5adcc2827/e975b27d-13d7-4e04-95f9-040a694e837d/b07820cb-5b3c-470b-9c73-9824ab4e0eef?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzFjNGJiZGIwLWQ3MjYtNGVhMi05YjliLTkwYTVhZGNjMjgyNy9lOTc1YjI3ZC0xM2Q3LTRlMDQtOTVmOS0wNDBhNjk0ZTgzN2QvYjA3ODIwY2ItNWIzYy00NzBiLTljNzMtOTgyNGFiNGUwZWVmIiwiaWF0IjoxNzE2MjM2NTU0LCJleHAiOjMzMjg2Nzk2NTU0fQ.6nlbIWzrnTO3gNWn1hlqmY5nqge_x0d1JmTT8hG2aB0 "=1501x")

**Additional context**
Configuration:

![Screenshot 2024-05-20 at 11 20 04 AM](https://uploads.linear.app/1c4bbdb0-d726-4ea2-9b9b-90a5adcc2827/b79c47ad-33db-4d6e-8f62-30f41a96d36e/6c6a1bb8-15ed-41f1-9218-be4f10fff6fd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzFjNGJiZGIwLWQ3MjYtNGVhMi05YjliLTkwYTVhZGNjMjgyNy9iNzljNDdhZC0zM2RiLTRkNmUtOGY2Mi0zMGY0MWE5NmQzNmUvNmM2YTFiYjgtMTVlZC00MWYxLTkyMTgtYmU0ZjEwZmZmNmZkIiwiaWF0IjoxNzE2MjM2NTU0LCJleHAiOjMzMjg2Nzk2NTU0fQ.\_mqPpJCX6D0Cke1NUcQFcf4XUidXKrtsBPOzrFR1M2E "=818x")

**Comment by Shahroz16** [comment]
Hey @rajAppmetry, thank you for reaching out. We have been unable to reproduce it, you mentioned to reproduce 

> Just initialising the customer io and opening the app crashing the app

Would you be able to share a sample app, where you can recreate this?

**Comment by eduard-smartify** [comment]
Same happens to me, although "luckily" it happens only on opening the app on a device while debugging, not on prod.

**Comment by Shahroz16** [comment]
Hey folks, thanks for writing in, yeah I suspect it's a very particular case where `WWebView` will fail to initialize in an emulator that would be in testing env. But we have noted it and the fix will be out soon.

**Comment by rajAppmetry** [comment]
Confirmed! It is not crashing now. Thanks for that :-) 

But now getting similar kind of crash (WKWebview) while initialising the MessagingInApp. If I comment that initialising then working perfectly fine. 

<img width="1512" alt="Screenshot 2024-05-28 at 9 14 47 AM" src="https://github.com/customerio/customerio-ios/assets/38988176/3107a638-5788-4dcd-a952-d6ffadd01bbc">
<img width="1030" alt="Screenshot 2024-05-28 at 9 15 27 AM" src="https://github.com/customerio/customerio-ios/assets/38988176/e25ac01f-5fd2-4f2d-909c-2641002ba57f">

**Comment by Ankish** [comment]
I am seeing this too.

**Comment by Shahroz16** [comment]
@rajAppmetry thats very strange, why would a real device not have web browser? is there anything specific about the device? I found something [similar](https://forums.developer.apple.com/forums/thread/747188) while looking maybe this is related?

**Comment by rajAppmetry** [comment]
No, it is a normal device. Actually it is crashing me for 2 of my devices  iphone X and 12 mini (17.4.1)
