### ISSUE TITLE
Enable per-notification suppression of notifications while in foreground

### ISSUE THREAD

**Issue by dfed** [customerio/customerio-ios#722]
**Is your feature request related to a problem? Please describe.**

I have some push notifications that I only want to show when the app is in the background, and others that I want to show when the app is in the foreground.

**Describe the solution you'd like**

I would like to implement my own `UNUserNotificationCenterDelegate` `func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification) async -> UNNotificationPresentationOptions` (or similar, CustomerIO-specific API) to selectively present or hide notifications based on the content of the notification.

**Comment by Shahroz16** [comment]
Hey @dfed thank you for reaching out, from what I understand, I think the use-case are describing should be possible if you utilize `Rich push`, where you add you add a notification service extension and can choose the push you want to hide/present. You can read more about it on the [docs](https://customer.io/docs/sdk/ios/push/rich-push/#1-add-a-service-extension-to-your-project). 

You can also have your own methods in `AppDelegate` to handle push notifications differently based on the app state.

**Comment by dfed** [comment]
> I think the use-case are describing should be possible if you utilize `Rich push`, where you add you add a notification service extension and can choose the push you want to hide/present

Apologies, I didn't clearly stated the problem. I am trying to control whether we show or hide push notifications while the app is in the foreground, based on the context in the push and the context on app state. I do not believe that a notification service extension is capable of communicating directly with the main application, so I do not believe this approach would work to solve my problem.

> You can also have your own methods in `AppDelegate` to handle push notifications differently based on the app state.

Which methods are you referring to? I'm aware of APIs on `UNUserNotificationCenterDelegate`, not `UIApplicationDelegate`, that can control whether notifications are shown while the app is foregrounded.

I tried implementing `UNUserNotificationCenterDelegate`'s `func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification) async -> UNNotificationPresentationOptions`. This method was called, but then [your implementation of this method](https://github.com/customerio/customerio-ios/blob/80a9d48c05eeb10bd4851fbdc41fe247c1f51ecf/Sources/MessagingPush/UserNotificationsFramework/UserNotificationsFrameworkAdapter.swift#L80-L92) explicitly overrode my decision [because the push came from CIO](https://github.com/customerio/customerio-ios/blob/80a9d48c05eeb10bd4851fbdc41fe247c1f51ecf/Sources/MessagingPush/PushHandling/iOSPushEventListener.swift#L96-L98).

What I'm looking for is per-push control over whether CIO push notifications are displayed. I believe that this isn't possible given the code I just linked.

**Comment by Shahroz16** [comment]
@dfed thanks for the detailed explanation. The code you pointed to only applies when automatic push tracking is enabled, which is by default. But you can do the following: 

- Disable the auto push feature
  - For [2.xx ](https://customer.io/docs/sdk/ios/2.x/push/#disable-automatic-push-tracking)
  - For [3.xx ](https://customer.io/docs/sdk/ios/push/push-setup/#1-initialize-the-push-service) 
- You must set their `AppDelegate` as the `UNNotificationCenter.delegate`
- [Forward the push click event to our SDK](https://customer.io/docs/sdk/ios/2.x/push/#metrics-userNotifications)
- Determine if the push is shown while the app is in foreground or not using, `userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification) as you have already mentioned.

**Comment by dfed** [comment]
Promising! Will try this today

**Comment by dfed** [comment]
And we're working! Thanks for the pointers. Closing.
