### ISSUE TITLE
App Crash in onPushAction completionHandler

### ISSUE THREAD

**Issue by vetrivelm** [customerio/customerio-ios#726]
In my app get crash when open app from received notification center.

**SDK version:** <3.2.0>

ℹ️ Received async completion handler from CioMessagingPush.UNUserNotificationCenterDelegateWrapper.

_Concurrency/CheckedContinuation.swift:167: Fatal error: SWIFT TASK CONTINUATION MISUSE: onPushAction(_:completionHandler:) tried to resume its continuation more than once, returning ()!

**Comment by Ahmed-Ali** [comment]
Hi @vetrivelm, any idea of this issue is consistent or if there is any specific setup that reproduces it?
I will try to see if I can reproduce but any details you can share would be super helpful

**Comment by Ahmed-Ali** [comment]
Another follow up question, if you turn on debug logs, do you happen to see a message like
`Received async completion handler from <DelegateClassName>`
repeated twice? we resume the continuation just after logging this message, if so, what do you see instead of `<DelegateClassName>` ?

**Comment by Ahmed-Ali** [comment]
I am working with the technical support team to respond to your support ticket, let's carry on there to keep the conversation in sync.

For future readers in case you are facing something similar: After local debugging, I believe there is something going on in the push delegate that I need to check out to understand what's causing this completion handler to be called twice.

A good place to start from is how the push integration looks like and specifically if you are setting a value for `UNUserNotificationCenter.current().delegate`, how is the implementation of `func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void)` looks like?

There is also a chance this is being set by a third party library you are using.

**Comment by vetrivelm** [comment]
> Another follow up question, if you turn on debug logs, do you happen to see a message like `Received async completion handler from <DelegateClassName>` repeated twice? we resume the continuation just after logging this message, if so, what do you see instead of `<DelegateClassName>` ?

**Comment by vetrivelm** [comment]
Yes, The following delegate method are fire two times even I get only one local notification 

func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void)

**Comment by Ahmed-CIO** [comment]
Happy this sorted it out!<br>While investigating this issue I updated our logs that would see the name of the delegate class that fires the completion handler. Hopefully this would make such issues easier to troubleshoot when you see the name of your delegate twice when you expect it to appear only ones

**Comment by S3Paramasivan** [comment]
Dear Friends, I have fixed similar issue by statement make sure that completionHandler() is called properly. Moved the statement to the first line inside the method userNotificationCenter(_:didReceive:withCompletionHandler:). Hope it will help someone. Thank you.
