### ISSUE TITLE
CioAnalytics library have wrong sources format

### ISSUE THREAD

**Issue by alpha-moisol** [customerio/customerio-ios#790]
**SDK version:** 3.3.2

**Environment:** Development

**Describe the bug**
Cannot install the library using Tuist. The problem is with dependency `CioAnalytics`. It does not have `Sources/CioAnalytics` folder, so, there is an error `Source path must be one of ["Sources/CioAnalytics", "Source/CioAnalytics", "src/CioAnalytics", "srcs/CioAnalytics"]`.

**To Reproduce**
Install CustomerIO 3.2.2 dependency using Tuist. Then run `tuist generate`

**Expected behavior**
CioAnalytics dependency has `Sources/CioAnalytics` folder.

**Comment by levibostian** [comment]
Hey there, Andrii. Sorry to hear that you have experienced this issue. Let me see if I can help. 

Could you provide your tuist config file so I can try and reproduce this error myself?

**Comment by alpha-moisol** [comment]
@levibostian Sure, this is `Package.swift` file:
```swift
// swift-tools-version: 5.9
import PackageDescription

#if TUIST
    import ProjectDescription

    let packageSettings = PackageSettings(
        productTypes: []
    )
#endif

let package = Package(
    name: "TestProj",
    dependencies: [
        .package(url: "https://github.com/customerio/customerio-ios", exact: "3.3.2")
    ]
)
```
and `Project.swift` file:
```swift
let project = Project(
    name: "TestProj",
    targets: [
        .target(
            name: "TestProj",
            destinations: .iOS,
            product: .app,
            bundleId: "com.testproj",
            sources: ["Sources/**/*.swift"],
            resources: ["Resources/**"],
            dependencies: [
                .external(name: "DataPipelines"),
                .external(name: "MessagingPushFCM")
            ]
        )
    ]
)
```

After `tuist install` command if you rename `./Tuist/.build/checkouts/cdp-analytics-swift/Sources/Segment` to `./Tuist/.build/checkouts/cdp-analytics-swift/Sources/CioAnalytics` everything works fine.

**Comment by levibostian** [comment]
Greatly appreciate the config files. 

From that, I have been able to reproduce the issue. 

We're working on a fix for this issue. We hope to get something out to you as soon as we can. We'll keep you updated here on the progress.

**Comment by levibostian** [comment]
@alpha-moisol, I have a fix for you to try out.  

If you update your `Package.swift` file to install the `customerio-ios` version `3.3.3` and run your `tuist install; tuist generate` functions again, see if the error goes away. 

I no longer see the error from testing on my machine. Hope the same goes for you!

**Comment by alpha-moisol** [comment]
@levibostian Hi, thanks. Now it works perfectly fine!
