### ISSUE TITLE
Update FirebaseMessaging Dependency in v2 Branch to Ensure Compatibility with Newer Firebase Versions

### ISSUE THREAD

**Issue by AristideVB** [customerio/customerio-ios#823]
### **Description:**

Hello Customer.io Team,

We are currently using the **Customer.io Flutter plugin**, which relies on the **v2 branch** of the Customer.io iOS SDK. However, the existing `FirebaseMessaging` dependency in v2 is outdated and causing compatibility issues when trying to build with the latest Firebase versions that include bug fixes for building themselves with **Xcode 16** 

Since the Customer.io Flutter plugin has not yet been updated to use the **v3 iOS SDK**, we are still dependent on v2. In order to resolve these compatibility issues without waiting for the Flutter plugin to update to support the v3 iOS SDK, we need to update the Firebase dependency in the **v2 branch** of the iOS SDK.

### **Proposed Change:**
- Update the `FirebaseMessaging` dependency in the v2 branch to allow versions `>= 8.7.0` and `< 12`. This will ensure compatibility with Xcode 16 and the latest Firebase versions, while maintaining support for projects using the v2.x SDK.

### **Impact:**
- This change will allow apps using the Customer.io Flutter plugin (which depends on the iOS SDK v2) to build and work with the latest Firebase versions, including compatibility with Xcode 16.

I have created a branch with the required **urgent** updates and will be submitting a pull request for your review. Thank you for your consideration!

**Comment by ami-aman** [comment]
Hi @AristideVB 

Thank you again for sharing great detail and opening the PR. I want to let you know that we've released the fix on iOS SDK version [2.14.2](https://github.com/customerio/customerio-ios/releases/tag/2.14.2) and is now available to be used in your flutter app.

I'll go ahead and close this issue but feel free to let us know if you face any issues.
